baseURL: "https://ochudi.netlify.app/"
languageCode: en-us
title: Chudi
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Chukwudi Ofoma"
    subtitle: I'm a motivated software developer with hands-on experience in developing software applications and websites using various frameworks and tools, and a strong foundation in programming, algorithms, and data structures.
    imageUrl: "home/me.jpg"
    imageWidth: 220
    imageHeight: 220
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/17SDV1Dq4_WAlCNfcBtdmHPZgSDHg9_6u/view"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:chukwudi.ofoma@pau.edu.ng"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/chukwudi-ofoma-106ab119a/"
    - name: "github"
      url: "https://github.com/ochudi"
    - name: "youtube"
      url: "https://www.youtube.com/@ochudi"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
